In [1]:
import torch
from torchvision import transforms
from PIL import Image
import numpy as np


# 实例化转换器
to_tensor = transforms.ToTensor()

print("=" * 60)
print("示例 1：PIL 彩色图像 (RGB)")
print("=" * 60)

# 创建一张 4x4 的 RGB 图像，并手动设置像素值
pil_img = Image.new('RGB', (4, 4))
pixels = pil_img.load()
for i in range(4):
    for j in range(4):
        pixels[i, j] = (255, 128, 0)  # R=255, G=128, B=0

tensor = to_tensor(pil_img)

示例 1：PIL 彩色图像 (RGB)


In [2]:
print(f"PIL 尺寸 (W, H) : {pil_img.size}")          # PIL 返回 (width, height)
print(f"PIL 模式       : {pil_img.mode}")           # 'RGB'
print(f"Tensor 形状    : {tensor.shape}")           # torch.Size([3, 4, 4])
print(f"Tensor 数据类型: {tensor.dtype}")           # torch.float32

PIL 尺寸 (W, H) : (4, 4)
PIL 模式       : RGB
Tensor 形状    : torch.Size([3, 4, 4])
Tensor 数据类型: torch.float32


In [3]:
# 验证数值缩放和维度调整
print(f"\n--- 第一个像素的三个通道值 ---")
print(f"R 通道 [0, 0, 0]: {tensor[0, 0, 0]:.4f}")   # 255/255 = 1.0000
print(f"G 通道 [1, 0, 0]: {tensor[1, 0, 0]:.4f}")   # 128/255 ≈ 0.5020
print(f"B 通道 [2, 0, 0]: {tensor[2, 0, 0]:.4f}")   # 0/255 = 0.0000


--- 第一个像素的三个通道值 ---
R 通道 [0, 0, 0]: 1.0000
G 通道 [1, 0, 0]: 0.5020
B 通道 [2, 0, 0]: 0.0000


In [4]:
print("\n" + "=" * 60)
print("示例 2：NumPy 灰度数组 (模拟 MNIST)")
print("=" * 60)

# 创建 28x28 的灰度图，数值范围 0-255
np_gray = np.random.randint(0, 256, (28, 28), dtype=np.uint8)
tensor_gray = to_tensor(np_gray)

print(f"NumPy 形状 (H, W)     : {np_gray.shape}")         # (28, 28)
print(f"NumPy 数据类型        : {np_gray.dtype}")        # uint8
print(f"NumPy 数值范围        : [{np_gray.min()}, {np_gray.max()}]")
print(f"Tensor 形状 (C, H, W) : {tensor_gray.shape}")     # (1, 28, 28)
print(f"Tensor 数据类型       : {tensor_gray.dtype}")     # float32
print(f"Tensor 数值范围       : [{tensor_gray.min():.4f}, {tensor_gray.max():.4f}]")

# 验证具体数值
r, c = 5, 10
print(f"\n验证：NumPy [{r}, {c}] = {np_gray[r, c]}")
print(f"      Tensor [0, {r}, {c}] = {tensor_gray[0, r, c]:.4f}")
print(f"      手动计算: {np_gray[r, c]} / 255 = {np_gray[r, c] / 255:.4f}")


print("\n" + "=" * 60)
print("示例 3：NumPy 彩色数组 (直观展示维度变化)")
print("=" * 60)

# 构造一个 2x2 的 RGB 数组，方便观察维度顺序
np_rgb = np.array([
    [[255, 0, 0],   [0, 255, 0]],    # 第0行: 红, 绿
    [[0, 0, 255],   [255, 255, 255]] # 第1行: 蓝, 白
], dtype=np.uint8)

print("原始 NumPy 数组 (H, W, C):")
print(np_rgb)
print(f"形状: {np_rgb.shape}")  # (2, 2, 3)

tensor_rgb = to_tensor(np_rgb)
print(f"\n转换后 Tensor (C, H, W):")
print(tensor_rgb)
print(f"形状: {tensor_rgb.shape}")  # (3, 2, 2)

# 逐通道展示
print(f"\nR 通道 (C=0):\n{tensor_rgb[0]}")
print(f"G 通道 (C=1):\n{tensor_rgb[1]}")
print(f"B 通道 (C=2):\n{tensor_rgb[2]}")


print("\n" + "=" * 60)
print("关键变化总结")
print("=" * 60)
print("1. 数值缩放: 像素值 [0, 255]  ->  [0.0, 1.0]  (除以 255)")
print("2. 维度调整: (H, W, C)        ->  (C, H, W)   (通道移到最前)")
print("3. 数据类型: uint8             ->  float32")
print("4. 灰度图  : (H, W)            ->  (1, H, W)   (自动补通道维)")


示例 2：NumPy 灰度数组 (模拟 MNIST)
NumPy 形状 (H, W)     : (28, 28)
NumPy 数据类型        : uint8
NumPy 数值范围        : [0, 255]
Tensor 形状 (C, H, W) : torch.Size([1, 28, 28])
Tensor 数据类型       : torch.float32
Tensor 数值范围       : [0.0000, 1.0000]

验证：NumPy [5, 10] = 136
      Tensor [0, 5, 10] = 0.5333
      手动计算: 136 / 255 = 0.5333

示例 3：NumPy 彩色数组 (直观展示维度变化)
原始 NumPy 数组 (H, W, C):
[[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255 255]]]
形状: (2, 2, 3)

转换后 Tensor (C, H, W):
tensor([[[1., 0.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.]],

        [[0., 0.],
         [1., 1.]]])
形状: torch.Size([3, 2, 2])

R 通道 (C=0):
tensor([[1., 0.],
        [0., 1.]])
G 通道 (C=1):
tensor([[0., 1.],
        [0., 1.]])
B 通道 (C=2):
tensor([[0., 0.],
        [1., 1.]])

关键变化总结
1. 数值缩放: 像素值 [0, 255]  ->  [0.0, 1.0]  (除以 255)
2. 维度调整: (H, W, C)        ->  (C, H, W)   (通道移到最前)
3. 数据类型: uint8             ->  float32
4. 灰度图  : (H, W)            ->  (1, H, W)   (自动补通道维)
