In [1]:
import numpy as np

# 设置随机种子保证可重复
np.random.seed(2024)

# ========== 参数设定 ==========
x_0 = np.array([100.0, 80.0, 60.0, 40.0])  # 2x2 图像拉平的4维向量
beta_t = 0.1

# 均值向量 μ = sqrt(1-β) * x_0
mu = np.sqrt(1 - beta_t) * x_0

# 协方差矩阵 Σ = β_t * I (4x4)
Sigma = beta_t * np.eye(4)

# ========== 方法1：直接从多元高斯采样 ==========
n_samples = 10
samples = np.random.multivariate_normal(mu, Sigma, size=n_samples)
print(samples)

# ========== 方法2：手动实现（重参数化技巧）==========
# 公式: x_t = sqrt(1-β) * x_{t-1} + sqrt(β) * ε
# 其中 ε ~ N(0, I)，即每个分量独立从标准正态采样
epsilon = np.random.randn(4)          # 4个独立标准正态随机数
x_t_manual = np.sqrt(1 - beta_t) * x_0 + np.sqrt(beta_t) * epsilon

[[95.39581268 76.12783367 56.85726605 37.89960937]
 [95.15801082 76.26159229 56.09249315 37.52823698]
 [95.01379098 75.92693541 57.25416053 38.46089929]
 [94.39378735 75.80680575 57.29857226 38.21986186]
 [94.73644827 75.8157535  57.21941486 37.70500322]
 [94.93417751 76.34014115 56.45010185 37.48064029]
 [95.18166292 75.61536186 56.80520037 37.46201558]
 [94.75715187 76.09702372 57.13895444 38.18679615]
 [94.41595025 75.7590403  56.70437811 37.90760079]
 [95.23028007 75.99813666 56.87776087 38.00399801]]
